# Testowac sobie mozna api

### Lista

GET http://127.0.0.1:5001/cocktails/
Accept: application/json

###

### Pojedynczy

GET http://127.0.0.1:5001/cocktails/apple-slammer
Accept: application/json

###

### Dodawanie - to zadziala
POST http://127.0.0.1:5001/cocktails/
Content-Type: application/json

{
  "ingredients": [
    {
      "name": "7-Up"
    }
  ],
  "instructions": [
    "make a drink"
  ],
  "name": "Example Cocktail",
  "slug": "example-cocktail"
}

###

### Jak widac jest i dało mu id (models/objectid.py tak robi)
GET http://127.0.0.1:5001/cocktails/example-cocktail
Accept: application/json

###


### Dodawanie - to nie zadziala, bo nie ma ingredients (w models definiujemy wymagane pola)

POST http://127.0.0.1:5001/cocktails/
Content-Type: application/json

{
  "ingredients": [
    {
      "name": "7-Up"
    }
  ],
  "instructions": [
    "make a drink"
  ],
  "name": "Example Cocktail",
  "slug": "example-cocktail"
}
