###
GET http://127.0.0.1:5001/articles/
Accept: application/json

###
GET http://127.0.0.1:5001/articles?page=2&per_page=4
Accept: application/json

###
GET http://127.0.0.1:5001/articles?page=1&per_page=3&sort=title
Accept: application/json

###
GET http://127.0.0.1:5001/articles/2
Accept: application/json

### Expect 404
GET http://127.0.0.1:5001/articles/21231213
Accept: application/json

###
POST http://127.0.0.1:5001/articles/
Content-Type: application/json

{
  "title": "Testowy artykul",
  "category": "test",
  "content": "Siema siema o tej porze.",
  "image_source": "https://source.unsplash.com/random/900x700/?car",
  "tags": [
    "test"
  ]
}

### Expect some 4xx
POST http://127.0.0.1:5001/articles/
Content-Type: application/json

{
  "title": "Testowy artykul",
  "hehe": "hehe"
}

### might wanna change id to delete
DELETE http://127.0.0.1:5001/articles/18
Content-Type: application/json

### By tag
GET http://127.0.0.1:5001/articles/tag/test
Content-Type: application/json

### By category
GET http://127.0.0.1:5001/articles/category/zoologia
Content-Type: application/json

