### Registering
POST http://127.0.0.1:5001/signup
Content-Type: application/json

{
  "login": "jan2",
  "password1": "hehe",
  "password2": "hehe",
  "name": "Jan"
}


### Logging in
POST http://127.0.0.1:5001/login
Content-Type: application/json

{
  "login": "jan2",
  "password": "hehe"
}


### Check the user
GET http://127.0.0.1:5001/users/18
Accept: application/json


### Recommendations just for logged in user
GET http://127.0.0.1:5001/articles/recommended
Content-Type: application/json


### Log out
POST http://127.0.0.1:5001/logout
